FROM ubuntu:22.04

# 作業ディレクトリを /works にする
WORKDIR /works

# 初期設定
RUN apt update -y

# ■ go言語
ENV GOVERSION 1.18.4
ENV ARCH amd64
ENV HOME /root
ENV PATH $PATH:/usr/local/go/bin
ENV GOPATH $HOME/work
ENV PATH $GOPATH/bin:$PATH

COPY scripts/install-tools-golang.sh /works/scripts/install-tools-golang.sh
RUN bash /works/scripts/install-tools-golang.sh

# ■ Python3言語
ENV PYTHONVERSION 3.10.5
ENV PYTHONVERSIONBIN 3.10

COPY scripts/install-tools-python3.sh /works/scripts/install-tools-python3.sh
RUN bash /works/scripts/install-tools-python3.sh

WORKDIR /works/app

ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
