FROM debian:bullseye-20230703-slim
#FROM --platform=linux/amd64 debian:bullseye-20230703-slim

# 作業ディレクトリを /works にする
WORKDIR /works

# 初期設定
RUN apt update -y
RUN apt install wget -y

# ■ JAVA
ENV JAVA_VERSION 23

COPY scripts/install-tools-java23.sh /works/scripts/install-tools-java.sh
RUN bash /works/scripts/install-tools-java.sh

# Export Java environment variables globally
ENV JAVA_HOME=/usr/java/jdk-${JAVA_VERSION}
ENV PATH=$JAVA_HOME/bin:$PATH
ENV CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib:$JAVA_HOME/lib/tools.jar

WORKDIR /works/app

ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
