FROM ubuntu:22.04

# 作業ディレクトリを /works にする
WORKDIR /works

# 初期設定
RUN apt update -y

# ■ c++言語
COPY scripts/install-tools-clang.sh /works/scripts/install-tools-clang.sh
RUN bash /works/scripts/install-tools-clang.sh

WORKDIR /works/app

ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
