FROM debian:bullseye-20230109-slim
#FROM ubuntu:22.04

# 作業ディレクトリを /works にする
WORKDIR /works

# 初期設定
RUN apt update -y

# ■ clang
COPY scripts/install-tools-debian-bullseye-clang15.sh /works/scripts/install-tools-clang.sh
RUN bash /works/scripts/install-tools-clang.sh

WORKDIR /works/app

ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
