FROM debian:bullseye-20230703-slim
#FROM ubuntu:22.04

# 作業ディレクトリを /works にする
WORKDIR /works

# 初期設定
RUN apt update -y

# ■ rust言語
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUSTVERSION=1.66.1

COPY scripts/install-tools-rust.sh /works/scripts/install-tools-rust.sh
RUN bash /works/scripts/install-tools-rust.sh

WORKDIR /works/app

ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
